// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProjetoWeb.Migrations
{
    [DbContext(typeof(ProjetoWebContext))]
    [Migration("20240924044036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoWeb.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasDiscriminator().HasValue("Funcionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoWeb.Models.Colaborador", b =>
                {
                    b.HasBaseType("ProjetoWeb.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Colaborador");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Financeiro", b =>
                {
                    b.HasBaseType("ProjetoWeb.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Financeiro");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Jardineiro", b =>
                {
                    b.HasBaseType("ProjetoWeb.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Jardineiro");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Master", b =>
                {
                    b.HasBaseType("ProjetoWeb.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Master");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Vendedor", b =>
                {
                    b.HasBaseType("ProjetoWeb.Models.Funcionario");

                    b.HasDiscriminator().HasValue("Vendedor");
                });
#pragma warning restore 612, 618
        }
    }
}
